#! /bin/sh

for fileName in `ls -a`; do
  #newFileName=`echo $fileName | sed -e 's/[0-9]*[0-9]\.\ //' -e 's/\ \-\ \[MusicJagat\.\Com\]//'`;
  #newFileName=`echo $fileName | sed -e 's/\ \@\ Fmw11\.com//'`;
  #newFileName=`echo $fileName | sed -e 's/[0-9]*[0-9]\ \-\ CE\ \-\ //' -e 's/\ \[DJMaza\]//'`;
  newFileName=`echo $fileName | sed -e 's/\(Bengalimp3\.IN\)//'`;
  mv "$fileName" "$newFileName";
done;
